# .NET Desktop
# Build and run tests for .NET Desktop or Windows classic desktop solutions.
# Add steps that publish symbols, save build artifacts, and more:
# https://docs.microsoft.com/azure/devops/pipelines/apps/windows/dot-net

trigger:
- develop
- master

pr:
  branches:
    include:
    - develop

pool:
  vmImage: 'VS2017-Win2016'

variables:
  buildPlatform: 'Any CPU'
  buildConfiguration: 'Release'
  Version: '1.0.$(Build.BuildId)'
  Major: '1'
  Minor: '0'
  Patch: '$(Build.BuildId)'
  testProject: 'tests/MGroup.IGA.Tests'

steps:
- task: DotNetCoreCLI@2
  name: dotnetRestore
  displayName: "Restore nugets"
  inputs:
    command: 'restore'
    verbosityRestore: 'Normal'
    feedRestore: 'MSolve-Nugets'

- task: SonarCloudPrepare@1
  displayName: "Prepares SonarCloud analysis (master)"
  condition: eq(variables['Build.SourceBranch'], 'refs/heads/master')
  inputs:
    SonarCloud: 'SonarCloud'
    organization: 'mgroupntua'
    scannerMode: 'MSBuild'
    projectKey: 'MSolve.IGA'
    extraProperties: 'sonar.cs.opencover.reportsPaths=$(Build.SourcesDirectory)/coverage/coverage.opencover.xml'

- task: UseGitVersion@5
  inputs:
    versionSpec: '5.x'
    useConfigFile: true

- task: DotNetCoreCLI@2
  name: dotnetBuild
  displayName: "Build projects"
  inputs:
    command: 'build'
    arguments: '-p:Version=$(GitVersion.SemVer)'
    verbosityPack: 'Minimal'
    configuration: '$(buildConfiguration)'

- script: |
    dotnet test --logger trx --no-build /p:CollectCoverage=true /p:CoverletOutputFormat=opencover /p:CoverletOutput=$(Build.SourcesDirectory)/coverage/ $(testProject)
  displayName: 'Runs tests (master)'
  condition: eq(variables['Build.SourceBranch'], 'refs/heads/master')


- task: SonarCloudAnalyze@1
  displayName: "Performs SonarCloud Analysis (master)"
  condition: eq(variables['Build.SourceBranch'], 'refs/heads/master')

- task: SonarCloudPublish@1
  displayName: 'Publish Quality Gate Results (master)'
  condition: eq(variables['Build.SourceBranch'], 'refs/heads/master')
  inputs:
    pollingTimeoutSec: '300'


- task: DotNetCoreCLI@2
  displayName: Runs Tests (develop)
  condition: eq(variables['Build.SourceBranch'], 'refs/heads/develop')
  inputs:
    command: 'test'
    projects: '**/*[Tt]ests/*.csproj'
    arguments: '--configuration $(BuildConfiguration) /p:CollectCoverage=true /p:CoverletOutputFormat=cobertura'
    publishTestResults: true

- task: reportgenerator@4
  displayName: Generate coverage report (develop)
  condition: eq(variables['Build.SourceBranch'], 'refs/heads/develop')
  inputs:
    reports: '**/coverage.cobertura.xml'
    targetdir: 'CoverageReport'

- task: PublishCodeCoverageResults@1
  displayName: Publish Code Coverage Results (develop)
  condition: eq(variables['Build.SourceBranch'], 'refs/heads/develop')
  inputs:
    codeCoverageTool: 'Cobertura'
    summaryFileLocation: '**/coverage.cobertura.xml'
    reportDirectory: 'CoverageReport'

- task: ResharperCli@2
  displayName: Code analysis (develop)
  condition: eq(variables['Build.SourceBranch'], 'refs/heads/develop')
  inputs:
    solutionOrProjectPath: 'MGroup.IGA.sln'
    failBuildLevelSelector: 'Warning'
    failBuildOnCodeIssues: false

- task: DotNetCoreCLI@2
  name: dotnetPack
  condition: ne(variables['Build.Reason'], 'PullRequest')
  displayName: "Packages new nugets"
  inputs:
    command: 'pack'
    versioningScheme: 'byEnvVar'
    versionEnvVar: '$(GitVersion.SemVer)'
    verbosityPack: 'Normal'

- task: PublishBuildArtifacts@1
  name: publishToFeed
  condition: ne(variables['Build.Reason'], 'PullRequest')
  displayName: "Publishes to pipeline artifacts"
  inputs:
    ArtifactName: 'drop'

- task: DotNetCoreCLI@2
  name: dotnetPushNugetPrivate
  condition: ne(variables['Build.Reason'], 'PullRequest')
  displayName: "Push nugets to private feed"
  inputs:
    command: 'push'
    packagesToPush: '$(build.artifactStagingDirectory)/*.nupkg'
    verbosityPack: 'Minimal'
    feedPublish: 'MSolve-Nugets'

- task: DotNetCoreCLI@2
  name: dotnetPushNugetPublic
  condition: ne(variables['Build.Reason'], 'PullRequest')
  displayName: "Push nugets to public feed"
  inputs:
    command: 'push'
    packagesToPush: '$(build.artifactStagingDirectory)/*.nupkg'
    verbosityPack: 'Minimal'
    feedPublish: 'MSolve/MGroup'

- task: DotNetCoreCLI@2
  enabled: false
  condition: ne(variables['Build.Reason'], 'PullRequest')
  name: dotnetPushSymbolPrivate
  displayName: "Publishes symbol nugets"
  inputs:
    command: 'push'
    searchPatternPush: '$(Build.ArtifactStagingDirectory)/*.snupkg'
    feedPublish: 'MSolve-Nugets'

- task: DotNetCoreCLI@2
  enabled: false
  condition: ne(variables['Build.Reason'], 'PullRequest')
  name: dotnetPushSymbolPublic
  displayName: "Publishes symbol nugets"
  inputs:
    command: 'push'
    searchPatternPush: '$(Build.ArtifactStagingDirectory)/*.snupkg'
    feedPublish: 'MSolve/MGroup'
